### ISSUE TITLE
August 18th Ideas

### ISSUE THREAD

**Issue by lukestringer90** [SheffieldSwift/Materials#1]
Preliminary idea: @domness (and possibly his co-developer) talk about what it's like to _actually_ build an app in Swift.

**Comment by lukestringer90** [comment]
Sheesh, I can't read a calendar apparently.

**Comment by lukestringer90** [comment]
Actually maybe this issue is better in the Operations repo?

**Comment by SheffieldKevin** [comment]
A show and tell meetup

**Comment by SheffieldKevin** [comment]
Ask Glyn Williams to talk about converting objc to Swift.

**Comment by SheffieldKevin** [comment]
Do a push for a week to see if we can get an external speaker in.

**Comment by lukestringer90** [comment]
Discuss [here](https://github.com/SheffieldSwift/Operations/issues/2) as the Operations repo is more appropriate for this.
